### ISSUE TITLE
CPU Only failed

### ISSUE THREAD

**Issue by hxhc** [lizeng614/SqueezeNet-Neural-Style-Pytorch#3]
Hi, I'm trying your model without cuda( no GPU, either), but it dropped an cuda runtime error:

```shell

RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/autograd/engine.cpp:353

```

So what should be installed or be configured?
I use python3.6 with anaconda.

**Comment by CoderInPajamas** [comment]
Hi,
sorry for replying to you this late, I just saw your question.
to solve your problem, you may want to check this:
https://github.com/pytorch/pytorch/issues/1159
https://github.com/pytorch/pytorch/issues/1154

**Comment by hxhc** [comment]
Thank you, I fixed it by upgrading my pytorch version from 0.1.11.post4 to 0.1.11.post5.
